### ISSUE TITLE
License needed

### ISSUE THREAD

**Issue by glikely** [aaronsnoswell/QMLVirtualJoystick#2]
Can you add a license to this project please? I'd like to use it in one of my projects, but I need to make sure you are providing it under a license that allows me to do that.

If you prefer, I can provide a pull request with whichever open source license you prefer. For something like this I would recommend a permissive license like BSD.

**Comment by aaronsnoswell** [comment]
Thanks @glikely! My go-to is MIT, added.

Cheers mate.
